### ISSUE TITLE
'jira-task-id-empty' is being emitted when the commit message separator is not ":"

### ISSUE THREAD

**Issue by jefferson-vieira** [Gherciu/commitlint-jira#12]
**'jira-task-id-empty' is being emitted when the commit message separator is not ":"**

Sample commit message:
`TEST-001 jira commit lint`

commitlint.config.js
```
module.exports = {
  plugins: ['commitlint-plugin-jira-rules'],
  extends: ['jira'],
  rules: {
    'jira-commit-message-separator': [2, 'always', ' ']
  }
};
```
result:
`the commit message must provide minimum one task id followed by (:) symbol, if task not have an id use a conventional task id e.g: "IB-0000: My commit message" [jira-
task-id-empty]`

**Comment by Gherciu** [comment]
@jefferson-vieira  at the moment only ":" and ": " are supported as 'jira-commit-message-separator' values because if you use this value " " what space we should use as separator to split this commit into parts like (ids, body etc.) `TEST-001" "jira" "commit" "lint`??? So, for this reason, I have added only 2 supported values in order to avoid incorrect parsing of commits messages.

**Comment by Gherciu** [comment]
@jefferson-vieira  I will keep this issue open till next release and notify you if we fix this issue.

**Comment by jefferson-vieira** [comment]
@Gherciu Thank you for your attention :)

**Comment by wonskarol** [comment]
> At the moment this thing is not documented because I have a few ideas about how to change it so at the next release this will be changed in order to fully support this feature.

@Gherciu do you know when the release will happen?

**Comment by antonio-rodrigues** [comment]
Thanks for the feedback!
Please, keeps us posted about the adopted solution.

**Comment by kaangokdemir** [comment]
Any updates?

**Comment by Gherciu** [comment]
@antonio-rodrigues @kaangokdemir @wonskarol .........sorry guys I tried several times but .......we definitelly need ":" as a separator or other unical symbol because SPACE symbol introduces a lot of area for bugs which is bad.....as I said earlier imagine we have a commit "IB-21 bla bla-1 bla-2 etc etc" ...it is impossible to determine where is the task ID if we split the message using the space  ..plus other people want the task ID at the end etc etc a lot of desires.....it's impossible to fit each need in only one plugin.... 

But the PR's are welcome ...if someone will manage to implement a really working solution for this format I'll be very happy to release this PR

**Comment by cierzniak** [comment]
I wanted to change use space-minus-space `( - )` since it's our company convention and it's not achievable 😕 

commitlint config:
```js
module.exports = {
  extends: ['jira'],
  plugins: ['commitlint-plugin-jira-rules'],
  rules: {
    'jira-task-id-separator': [2, 'always', '-'],
    'jira-commit-message-separator': [2, 'always', ' - '],
    'jira-task-id-project-key': [2, 'always', ['OPT']],
  },
};
```
and usage:
```shell
$ echo "OPT-123 - Dummy test commit message" | yarn commitlint
✖   the commit message must provide minimum one task id followed by (:) symbol, if task does not have an id use a conventional task id e.g: "IB-0000: My commit message" [jira-task-id-empty]

✖   found 1 problems, 0 warnings

$ echo "OPT-123: Dummy test commit message" | yarn commitlint
✖   Commit message parts must be separated with " - " e.g: IB-2121 - My commit message body [jira-commit-message-separator]

✖   found 1 problems, 0 warnings
```

Why do you allow to configure this while it's fixed to only one result?

BTW great job!

**Comment by cierzniak** [comment]
I wanted to change use space-minus-space `( - )` since it's our company convention and it's not achievable 😕 

commitlint config:
```js
module.exports = {
  extends: ['jira'],
  plugins: ['commitlint-plugin-jira-rules'],
  rules: {
    'jira-task-id-separator': [2, 'always', '-'],
    'jira-commit-message-separator': [2, 'always', ' - '],
    'jira-task-id-project-key': [2, 'always', ['OPT']],
  },
};
```
and usage:
```shell
$ echo "OPT-123 - Dummy test commit message" | yarn commitlint
✖   the commit message must provide minimum one task id followed by (:) symbol, if task does not have an id use a conventional task id e.g: "IB-0000: My commit message" [jira-task-id-empty]

✖   found 1 problems, 0 warnings

$ echo "OPT-123: Dummy test commit message" | yarn commitlint
✖   Commit message parts must be separated with " - " e.g: IB-2121 - My commit message body [jira-commit-message-separator]

✖   found 1 problems, 0 warnings
```

Why do you allow to configure this while it's fixed to only one result?

BTW great job!
